### ISSUE TITLE
Resizing terminal

### ISSUE THREAD

**Issue by salt-die** [salt-die/terminal_dungeon#1]
curses doesn't seem to detect any change in getmaxyx after a resize.  I've gone so far as to implement my own signal handler for SIGWINCH and reinitialize the screen if there is a resize, but still no changes.  Have no idea what's going on.

**Comment by salt-die** [comment]
os.get_terminal_size() from the os module does seem to give correct terminal dimensions even with the keyboard listener, but naive implementations have run into key errors -- I may pursue this further though.

**Comment by salt-die** [comment]
Latest commit finally fixes this issue!

**Comment by thenger** [comment]
For ref : 3c2804207a25c41f04262649f8ccdd3a234e63d0

So, no problems with os.get_terminal_size() ?

**Comment by salt-die** [comment]
os.get_terminal_size works for me with the Listener threads on Ubuntu at least.
